services:
  - type: web
    name: inventario-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: GRAPH_SENDER_MAILBOX
        sync: false
      - key: CORS_ORIGIN
        value: "*"
